name: Build and push Docker image

on:
  #schedule:
  #  - cron: '0 0 */7 * *'
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Change repository name to lowercase
      env:
        repo: "${{ github.repository }}"
      run: |
        echo "REPOSITORY=${repo,,}" >> ${GITHUB_ENV}
        
    - name: Versioning
      id: ver
      run: |
        VERSION=latest
        
        if [[ ${{ github.ref_name }} != "master" ]]; then
          VERSION=${{ github.ref_name }}
        fi
        TAGS="${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${VERSION}"
        
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=docker_image::${{ env.REPOSITORY }}
        
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log into registry (${{ env.REGISTRY }})
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
        push: true
        tags: ${{ steps.ver.outputs.tags }}
